core_reader: include sys/stat.h for fstat()
We need to include sys/stat.h because we use the fstat() function.
With newer glibc versions, we get a build failure otherwise:

src/client/linux/minidump_writer/core_reader.cc: In function
	'bool MmapAndValidateCoreFile(const char*, void**, off_t*)':
src/client/linux/minidump_writer/core_reader.cc:27:16: error:
	'fstat' was not declared in this scope

BUG=chromium-os:24046
TEST=`emerge google-breakpad` now works with glibc-2.14

Change-Id: Iba209582079d0b5db22c91426b4cf5483b2f9bad
Reviewed-on: https://gerrit.chromium.org/gerrit/12712
Reviewed-by: Ben Chan <benchan@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>