Pin dump_syms to C++20
Just like disasm, dump_sys has build errors with C++23 so we need to pin
it to C++20 since we update google-breakpad easily. I am pinning to
gnu++20 specifically so there is no change to module since c++20 has
some differences to gnu++20.

Error:
prebuilts/clang/host/linux-x86/clang-r584948b/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'google_breakpad::DwpReader'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");

Bug: 429048222
Test: m dump_syms
Change-Id: Iff39551f3fc10345c7b7e559a244cece957d484e